task:
  bootstrap_script: |
    curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  matrix:
    - container:
        image: node:latest
      name: NodeLatest
    - container:
        image: node:carbon-jessie
      name: NodeCarbon
    - container:
        image: node:dubnium-jessie
      name: NodeDubnium
  yarn_cache:
    folder: node_modules
    fingerprint_script:
      - cat package.json
      - cat yarn.lock
    populate_script: yarn
  test_script: yarn test
