container:
  image: node:latest

test_task:
  auto_cancellation: false
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json
    populate_script: npm i
  test_script: npm test
