task:
  matrix:
    - container:
        image: node:latest
      name: NodeLatest
    - container:
        image: node:carbon-jessie
      name: NodeCarbon
    - container:
        image: node:dubnium-jessie
      name: NodeDubnium
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - cat package.json
    populate_script: npm i
  test_script: npm test
