container:
  image: node:latest
  cpu: 4
  memory: 10G

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json && cat package-lock.json
    populate_script: npm install
  test_script: npm test
