language: node_js
sudo: required
os:
  - osx
node_js:
  - node
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
before_install:
  - "echo Getting ready to install requirements from package.json file!  "
install:
  - npm install
after_install:
  - "echo Finished installing from package.json file!  "
before_script:
  - "echo Getting ready to test!  "
script:
  - npm test
after_script:
  - "echo Finished test script!  "
after_success:
  - "echo Build finished, the app built without any problems!  Yay!  "
after_failure:
  - "echo Build finished, the app built with problems.  How sad.  "
